### ISSUE TITLE
什么时候可以使用？

### ISSUE THREAD

**Issue by jiasaichao** [qiuxiang/react-native-baidumap-sdk#1]

**Comment by qiuxiang** [comment]
你要用也可以，我现在就已经用在新项目上了，只是短时间内只做自己需要的接口，iOS 的支持也要往后推迟。现在的 android 版基本的接口都已经有了的，如果你感兴趣，可以下载 [example.apk](https://github.com/qiuxiang/react-native-baidumap-sdk/releases/download/v0.1.6/example.apk) 看看都实现了什么。

相比于高德地图，百度地图更流畅（ios 差不多，android 差距明显），这次我重新设计了接口，和之前的高德地图项目比，这个库的定位模块是独立的，并且实现了点聚合。

**Comment by jiasaichao** [comment]
example.apk 这个我看了，实现的还不错，想用但是安装说明没有直接用pod安装就行吗？对于我这种不懂原生开发的弄不上啊。ios你想什么时候推出？比较在意安卓ios都需要支持。

**Comment by qiuxiang** [comment]
这个库要发展到比较易用，也得一个月吧，我不可能总是有时间做开源项目

**Comment by qiuxiang** [comment]
不过这个库我是打算主力维护的，计划做到比 react-native-amap3d 更好

**Comment by jiasaichao** [comment]
那太感谢你了，希望你长期维护

**Comment by qiuxiang** [comment]
现在已经基本可用了
