### ISSUE TITLE
百度地图只有空白网格

### ISSUE THREAD

**Issue by hphpwj** [qiuxiang/react-native-baidumap-sdk#10]
百度地图只有空白网格，感觉应该是百度AK的原因，但弄了半天也弄不出来，求帮忙，感觉keystore没有作用啊

**Comment by hphpwj** [comment]
哦，百度AK认证状态还是“未认证”，等认证通过后再试试

**Comment by qiuxiang** [comment]
你是运行的新项目还是 example？

**Comment by qiuxiang** [comment]
我的状态也是未认证，这并不影响

**Comment by kevinchensd** [comment]
昨天碰到了同样的问题，是Key的配置问题，默认配置的debug keystore是没法使用百度地图的，可以让release和debug使用同一个keystore文件，如可以在build.gradle里面这样配置，加上debug部分：buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }

        debug {
            signingConfig signingConfigs.release
        }

    }

**Comment by kevinchensd** [comment]
`    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }

        debug {
            signingConfig signingConfigs.release
        }

    }`

**Comment by qiuxiang** [comment]
@kevinchensd 我已经在昨天就改过了 https://github.com/qiuxiang/react-native-baidumap-sdk/commit/b73dcbdc8904b9d5716492a93e82dda7033f42ef 只是将 debug 设置成使用 release 一样的 signingConfig 还不行，还要把 keystore 放到项目。

**Comment by hphpwj** [comment]
@qiuxiang 我是运行的新项目，调用您的模块，哈哈，感觉你做的非常棒，尽管我还没弄出来，哈哈

**Comment by qiuxiang** [comment]
你上面的还没回答我

**Comment by hphpwj** [comment]
@qiuxiang @kevinchensd 已经OK了，感觉应该是没有在build明确debug版本中使用keystore的原因，只添加了release版本的，谢谢两位，这两天一直在等百度通过AK认证，结果未认证也没关系，哈哈
