### ISSUE TITLE
关于引入sdk后，再次触发“native module cannot be null”错误的问题

### ISSUE THREAD

**Issue by balflare** [qiuxiang/react-native-baidumap-sdk#100]
前提：

我的工程使用ios11,iphone X的模拟器进行运行，在没有引入地图模块之前，本身可以正常运行。在调试过程中，出现过一次“native module cannot be null”的错误，当时是采用了手动链接的方式，将“PushNotificationIOS”，“LinkingIOS”链接到xcode的libriary里，解决了这个问题，并正常运行。

问题：

现在引入您的这个SDK以后，在android模拟器、真机上都可以正常运行了。在移入ios环境之后，再次出现了“native module cannot be null”的错误。

错误信息定位在您工程目录下的location.js文件中的第六行，即如下语句中加粗的部分

import { NativeModules, NativeEventEmitter } from 'react-native'
import type { Location } from '../types'

const { BaiduMapLocation } = NativeModules
**const eventEmitter = new NativeEventEmitter(BaiduMapLocation)**

也就是该BaiduMapLocation没有被判定在NativeModules中。

**Comment by qiuxiang** [comment]
这就需要自己配置了

**Comment by balflare** [comment]
@qiuxiang 能否提供一点思路，这个 BaiduMapLocation需要如何能够正确的加入到NativeModule中去。

**Comment by balflare** [comment]
经过调试，解决了这个问题。方法是修改Podfile的内容，将最后一部分改为如下：

 pod 'react-native-baidumap-sdk', path: '../node_modules/react-native-baidumap-sdk/lib/ios'**,:subspaces => ['BaiduMapLocation']**

加粗的部分是添加上去的内容，需要手动指出react-native-baidumap-sdk的依赖模块，然后再使用pod install进行配置。

**Comment by qiuxiang** [comment]
这个项目的 podspec 根本就没有 subspaces 呀

**Comment by Warlock1994** [comment]
我感觉是用pod install 后会在targets出现一个奇怪的引用造成的问题，是不是pod脚本有什么问题
![image](https://user-images.githubusercontent.com/21231664/44589281-b83d2180-a7ea-11e8-9aed-2c6f357b1392.png)

**Comment by shizongli94** [comment]
遇到了同样的问题，确实需要在Podfile最后一行加上   **,:subspaces => ['BaiduMapLocation']**   的部分，否则会一直显示“native module cannot be null”的红屏错误提示。

在修改好Podfile后，再运行一次pod install。最后再重新来一次**react-native run-ios**命令
