### ISSUE TITLE
Cricle 圆形覆盖物 初始化错误？

### ISSUE THREAD

**Issue by knowledges** [qiuxiang/react-native-baidumap-sdk#108]
@qiuxiang 
代码：
```
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';

import {Initializer, MapView, Location} from 'react-native-baidumap-sdk';

Initializer.init()

export default class App extends Component<{}> {
  constructor (props) {
    super(props);
  }

  render() {
    return (
        <View style={{flex: 1}}>
          <MapView
              style={styles.container}
              center={{ latitude: 32.285513, longitude: 119.203448 }}
              zoomLevel={15}
              scaleBarDisabled={false} // 是否禁用比例尺
              overlookDisabled={true} // 是否禁用倾斜手势
          >
            <MapView.Marker
                color="#3498db"
                coordinate={{ latitude: 32.285513, longitude: 119.203448 }}
                selected={true}
            >
            </MapView.Marker>
            <MapView.Cricle
                center={{ latitude: 32.285513, longitude: 119.203448 }}
                radius={500}
                strokeWidth={1}
                strokeColor="rgba(0, 0, 255, 0.5)"
                fillColor="rgba(255, 0, 0, 0.5)"
            ></MapView.Cricle>
          </MapView>
        </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    width: 400,
    height: 300,
  }
});

```
圆形覆盖物需要引入什么吗？
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.

This error is located at:
    in BaiduMapView (at map-view.js:96)
    in MapView (at App.js:69)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
createFiberFromElement
    ReactNativeRenderer-dev.js:5103:6
reconcileSingleElement
    ReactNativeRenderer-dev.js:7379:8
reconcileChildFibers
    ReactNativeRenderer-dev.js:7529:14
reconcileChildrenAtExpirationTime
    ReactNativeRenderer-dev.js:7730:8
reconcileChildren
    ReactNativeRenderer-dev.js:7711:6
updateHostComponent
    ReactNativeRenderer-dev.js:8011:22
beginWork
    ReactNativeRenderer-dev.js:8293:10
performUnitOfWork
    ReactNativeRenderer-dev.js:10513:25
workLoop
    ReactNativeRenderer-dev.js:10584:43
_invokeGuardedCallback
    ReactNativeRenderer-dev.js:134:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:67:32
renderRoot
    ReactNativeRenderer-dev.js:10677:30
performWorkOnRoot
    ReactNativeRenderer-dev.js:11449:34
performWork
    ReactNativeRenderer-dev.js:11364:8
requestWork
    ReactNativeRenderer-dev.js:11258:18
scheduleWorkImpl
    ReactNativeRenderer-dev.js:11099:22
scheduleWork
    ReactNativeRenderer-dev.js:11046:28
scheduleRootUpdate
    ReactNativeRenderer-dev.js:11690:17
updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:11724:30
updateContainer
    ReactNativeRenderer-dev.js:11743:8
render
    ReactNativeRenderer-dev.js:12919:35
renderApplication
    renderApplication.js:58:21
run
    AppRegistry.js:104:10
runApplication
    AppRegistry.js:196:26
__callFunction
    MessageQueue.js:353:47
<unknown>
    MessageQueue.js:118:26
__guardSafe
    MessageQueue.js:316:6
callFunctionReturnFlushedQueue
    MessageQueue.js:117:17

**Comment by qiuxiang** [comment]
你确定这是 Cricle 导致的问题？

**Comment by knowledges** [comment]
@qiuxiang 是的，肯定。我才看到。你回的信息，刚下班？
我想实现的效果就是地图中心有一个坐标，以坐标为中心，向外画一个半径500米的圆形覆盖物；

**Comment by qiuxiang** [comment]
丘。。

看错误提示，就是你的 render 方法有问题呀，也说得很清楚

**Comment by knowledges** [comment]
@qiuxiang 
那应该怎么写啊？
我一开始添加坐标是对的，代码：
```
render() {
    return (
        <View style={{flex: 1}}>
          <MapView
              style={styles.container}
              center={{ latitude: 32.285513, longitude: 119.203448 }}
              zoomLevel={15}
              scaleBarDisabled={false} // 是否禁用比例尺
              overlookDisabled={true} // 是否禁用倾斜手势
          >
            <MapView.Marker
                color="#3498db"
                coordinate={{ latitude: 32.285513, longitude: 119.203448 }}
                selected={true}
            >
            </MapView.Marker>
          </MapView>
        </View>
    );
  }
```

然后我就想再画一个覆盖物，就包了上面的错，代码：
```
 <MapView >          
            <MapView.Cricle
                center={{ latitude: 32.285513, longitude: 119.203448 }}
                radius={500}
                strokeWidth={1}
                strokeColor="rgba(0, 0, 255, 0.5)"
                fillColor="rgba(255, 0, 0, 0.5)"
            ></MapView.Cricle>
</MapView>
```
然后我就想是不是该结合起来用，就变成上面的代码样子的！那你说我render 方法错了，能帮我改一下吗？

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/example/examples/overlays/circle.js

你自己看 example

**Comment by knowledges** [comment]
@qiuxiang 上面的问题好的。想请教一个问题：
MapView 中 Location 这个属性是不是必须要有一个默认值且不能为 null？
我在 componentDidMount 中 获取定位信息，想把定位赋值给  MapView 中 Location ；但是每次先执行了render ，报错说 Location 不能 为null！这样问题的解决方式说不是要初始化一个 location的坐标数据，不能为null？ 对吗

**Comment by qiuxiang** [comment]
你都不看 example 的吗 https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/example/examples/location/map-view.js

location 可以是 undefined、{} 但不能是 null
