### ISSUE TITLE
定位标志是否具有方向属性

### ISSUE THREAD

**Issue by MoonBlueSky** [qiuxiang/react-native-baidumap-sdk#109]
你好，我想知道定位标志是否具有方向属性，即定位后显示当前方向，有一个小三角指向

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/lib/js/map-view/map-view.js#L39
https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/lib/js/types.js#L28

**Comment by MoonBlueSky** [comment]
@qiuxiang  在这样设置之后，里面的方向属性似乎是-1，我打开您的示例中的Location in MapView页面，其中好像也没有像您截图的哪样有方向。

**Comment by qiuxiang** [comment]
方向是 gps 定位才返回的，是行进方向，你如果要跟随手机旋转的方向，那你需要另外获取手机罗盘的方向。

**Comment by MoonBlueSky** [comment]
那怎么才能在react native 中调取手机罗盘的相关数据呢？

**Comment by qiuxiang** [comment]
你就找找是不是有相关的库实现

**Comment by MoonBlueSky** [comment]
好的，但是我在github找了一圈，有一个库但太久了已经没有维护了，不知道作者后续是否有添加此功能的意图呢

**Comment by MoonBlueSky** [comment]
问题已经解决了啦，我发现一个关于罗盘的库并使用了它（[react-native-simple-compass](https://github.com/vnil/react-native-simple-compass)），谢谢大佬的解答哈哈
