### ISSUE TITLE
真机运行出错（react-native run-android）

### ISSUE THREAD

**Issue by knowledges** [qiuxiang/react-native-baidumap-sdk#110]
Attempt to read from field 'com.baidu.mapapi.model.LatLng.latitude' on a null object reference? 需要引入包文件吗？

**Comment by knowledges** [comment]
![wechatimg2874](https://user-images.githubusercontent.com/8423645/44849104-a6aaae00-ac1e-11e8-98f1-07b19ad561dd.png)

**Comment by knowledges** [comment]
然后我在 baidumapviewmanager.kt \baidumapview.kt 中尝试这引入这个包，提示：`Cannot import 'latitude', functions and properties can be imported only from packages or objects`

**Comment by qiuxiang** [comment]
你的 js 怎么写的？

**Comment by knowledges** [comment]
`import React, { Component } from 'react';
import { Text, View, Image, StyleSheet, TouchableOpacity, Dimensions, Button } from 'react-native';
import { DeviceInfo } from '../../config';
import {Initializer, MapView, Location} from 'react-native-baidumap-sdk';

Initializer.init().catch(e => console.error(e))

class HomeTabScreen extends Component {

    constructor (props) {
        super(props);
        // 隐藏导航
        this.props.navigator.toggleNavBar({
            to: 'hidden', // required, 'hidden' = hide navigation bar, 'shown' = show navigation bar
            animated: false // does the toggle have transition animation or does it happen immediately (optional). By default animated: true
        });
    }
    state = { };

    componentDidMount() {
      Location.init();
      Location.setOptions({ gps: true })
      Location.addLocationListener(location => {
        alert(JSON.stringify(location))
        this.setState({ location })
      });
      Location.start()
    }

    componentWillUnmount() {
      Location.stop()
      this.listener.remove()
    }

    add () {

    }

    render () {
        return (
            <View style={styles.container}>
                <View style={styles.header}>
                    <TouchableOpacity style={styles.headerLeftBtn} onPress={() => {}}>
                        <Image
                            style={styles.headerLeftImage}
                            source={require('../../assets/user.png')}
                        />
                    </TouchableOpacity>
                    <Text  style={styles.headerTitle}>千米红包定制开发</Text>
                    <TouchableOpacity style={styles.headerRightBtn} onPress={() => {}}>
                        <Image
                            style={styles.headerRightImage}
                            source={require('../../assets/wallet.png')}
                        />
                    </TouchableOpacity>
                </View>
                <View style={styles.bodys}>
                    <MapView
                        center={{latitude: 32.05126, longitude: 118.795536}}
                        location={{latitude: 32.05126, longitude: 118.795536}}
                        style={styles.map}
                        locationEnabled
                        zoomControlsDisabled
                        zoomLevel={15}
                        scaleBarDisabled={false} // 是否禁用比例尺
                        overlookDisabled={true} // 是否禁用倾斜手势
                    >
                        <MapView.Circle
                            center={{latitude: 32.05126, longitude: 118.795536}}
                            radius={1000}
                            strokeWidth={1}
                            strokeColor="#999"
                            fillColor="rgba(199, 199, 199, 0.5)"
                        />
                    </MapView>
                </View>
                <View>
                    <Button
                        onPress={() => alert('left')}
                        title='刷新'
                        color="#841584"
                    />

                    <Button
                        onPress={() => alert('right')}
                        title='新增坐标点'
                        color="#841584"
                    />
                </View>
            </View>
        )
    }
}


const styles = StyleSheet.create({
   container: {
       flex:1,
       backgroundColor: '#F5FCFF',
   },
   header: {
       flexDirection: 'row',
       height: 44,
       backgroundColor: '#FFF',
   },
   headerLeftBtn: {
       justifyContent: 'center',
       alignItems: 'center',
       width: 50,
       height: 44,
   },
   headerLeftImage: {
       width: 24,
       height: 24,
   },
   headerRightBtn: {
       justifyContent: 'center',
       alignItems: 'center',
       width: 50,
       height: 44,
   },
   headerRightImage: {
       width: 24,
       height: 24,
   },
   headerTitle: {
       flex: 1,
       paddingTop: 12,
       color: '#333',
       fontSize: 16,
       textAlign: 'center',
       fontWeight: '700',
   },
   bodys: {
       flex: 1,
   },
   map: {
       flex: 1,
       width: DeviceInfo.WIDTH,
       height: DeviceInfo.HEIGHT-44,
   }
});

export default HomeTabScreen;`

**Comment by knowledges** [comment]
0.47。0 版本支持吗？

**Comment by qiuxiang** [comment]
这个很显然是 jsx 用法不正确造成的，你先自己看吧
