### ISSUE TITLE
用户拒绝授权地理位置，仍然会进行定位

### ISSUE THREAD

**Issue by ImagineZzf** [qiuxiang/react-native-baidumap-sdk#114]
用户拒绝授权地理位置，仍然会进行定位，是使用了网络定位吗？如何移除？
`<!--<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />-->`
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

我把上边的注释了，但是还是会定位

**Comment by qiuxiang** [comment]
ACCESS_FINE_LOCATION 就是 GPS 定位，网络定位并不受限这个权限，不明白你想表达什么，这属于 SDK 的问题，或许你应该找官方社区，我也没法给你全面的解释
