### ISSUE TITLE
polyline data reload dynamic 

### ISSUE THREAD

**Issue by jenisoft613** [qiuxiang/react-native-baidumap-sdk#119]
Hello, Mr.qiuxiang.

I am very happy you provide excellent source code for baidumap.
I am using it on my project.

All is good . But I have not find solution for reload ployline when state is changed.
Please let me know how to use in this case.

Thanks, Jeni

**Comment by qiuxiang** [comment]
iOS or Android?

**Comment by jenisoft613** [comment]
both platform

**Comment by qiuxiang** [comment]
I tested it in android is no problem.
