### ISSUE TITLE
使用cocoapods接入sdk完成后，使用时报节点找不到。

### ISSUE THREAD

**Issue by black1997** [qiuxiang/react-native-baidumap-sdk#12]
接入成功后完成后，
import { MapView } from 'react-native-baidumap-sdk';
出现错误
![simulator screen shot - iphone 6 - 2018-02-24 at 17 21 28](https://user-images.githubusercontent.com/15035749/36628482-dd0cb0f8-1987-11e8-855f-038de5e03fb7.png)

**Comment by black1997** [comment]
![wx20180224-172841](https://user-images.githubusercontent.com/15035749/36628639-379ed4c4-1988-11e8-8508-643e2afe9982.png)

**Comment by qiuxiang** [comment]
很大的可能是你本地问题，无法确定为什么 `UnimplementedView` 会不存在，RN 内置模块都是要用到这个模块的。

你可以尝试改下 `text.ios.js`，先忽略这个错误，反正这段代码也没什么用。

**Comment by linwenchao** [comment]
相同的问题，试过 0.53.x 0.52.2 0.52.3 都是一样，但直接clone后运行就没问题……
