### ISSUE TITLE
setCustomMapStylePath 应该怎么加

### ISSUE THREAD

**Issue by Jackjianglin** [qiuxiang/react-native-baidumap-sdk#120]
如果我想自定义地图样式, 修改源码的话, 大概要怎么操作?

**Comment by qiuxiang** [comment]
去看官方的文档

**Comment by Jackjianglin** [comment]
百度地图官方的设置个性化地图样式, 是这一句代码setCustomMapStylePath.
我应该怎么加到你提供的组件中去, 让组件有这样一个功能

**Comment by dairf189** [comment]
这个问题最后解决了吗？ @Jackjianglin
