### ISSUE TITLE
can't create handler inside thread 

### ISSUE THREAD

**Issue by suwu150** [qiuxiang/react-native-baidumap-sdk#150]
![image](https://user-images.githubusercontent.com/20339760/50055601-f2607380-018b-11e9-8f30-94066362aeb6.png)

**Comment by qiuxiang** [comment]
这是 SDK 没初始化呀

**Comment by qiuxiang** [comment]
Initializer.init 需要 await

**Comment by suwu150** [comment]
我这样做了,还是同样的提示:
```
import { Initializer } from 'react-native-baidumap-sdk';
export default class App extends Component {
  constructor(props) {
    super(props);
    if (Platform.OS === 'android') {
      this._init();
    }
  }

  _init = async () => {
    await Initializer.init('ZtPacaifDuRwkoZWoM5u66rzx4mWsAjU').catch(e => console.error(e));
  };
```
1.我这边只需要获取到经纬度信息,也需要全部初始化吗?
2.这个初始化功能建议放置到内部处理,在添加modules的时候就默认初始化

**Comment by qiuxiang** [comment]
SDK 的初始化是必须的，location 的 初始化也要等到 SDK 的初始化之后。

虽然可以静默初始化，但失去了灵活性：不能传递 key，不能捕获错误。

你上面的代码都没有调用 location 的 init 怎么可能还是一样的错误呢。

**Comment by qiuxiang** [comment]
不对，有点奇怪，你创建一个可重现的项目放到 github，我在本地看看是不是可以重现

**Comment by suwu150** [comment]
我重新去创建项目进行测试,没有发现问题,在我现有的项目中,我看了下,有一个库里边是集成了百度定位的,是不是与这个有关系

**Comment by qiuxiang** [comment]
没有。。都没有考虑过这个问题

**Comment by suwu150** [comment]
好的,谢谢

**Comment by suwu150** [comment]
我这边根据我项目中其他库导入的百度定位包重新写了一下底层的定位功能,手动做了一个桥接,然后获取到经纬度定位信息,如果有和我想通情况的,可以参见我这边的桥接方式:[具体桥接方式---六、安卓中遇到的问题解决方案](https://blog.csdn.net/suwu150/article/details/80935563),代码在github地址能够查看[github实现代码](https://github.com/suwu150/react-native-locations)
