### ISSUE TITLE
显示空白是为什么？？

### ISSUE THREAD

**Issue by aLexdcl** [qiuxiang/react-native-baidumap-sdk#151]
安装成功，没有任何报错，但是 mapView 没有任何显示，安卓模拟器，能帮我看下是什么问题吗？

import { Initializer, MapView } from 'react-native-baidumap-sdk'

Initializer.init('iOS 开发密钥').catch(e => console.error(e))

export default class App extends Component<Props> {
  render() {
    return (
      <MapView center={{ latitude: 39.2, longitude: 112.4 }}/>
    );
  }
}

**Comment by suwu150** [comment]
真机试试

**Comment by aLexdcl** [comment]
第一次用没注意，没有设置大小
  <MapView  style={StyleSheet.absoluteFill}  center={{ latitude: 39.2, longitude: 112.4 }}/>
这样才有用

**Comment by les10281502** [comment]
请问你的是显示出地图了吗？我这边显示的是网格

**Comment by qiuxiang** [comment]
显示网格基本是因为 key 不对
