### ISSUE TITLE
用Geocode通过经纬度查询城市地址报错

### ISSUE THREAD

**Issue by horou-dsk** [qiuxiang/react-native-baidumap-sdk#162]
`Geocode.reverse({ latitude: 39, longitude: 113 }).then(result => {
        console.log(result);
      }).catch(err => {
        console.log(err);
      });`
会报这个错误

Error
    at createErrorFromErrorData

**Comment by qiuxiang** [comment]
android or ios？

**Comment by horou-dsk** [comment]
Android

**Comment by qiuxiang** [comment]
android 我没有能重现

**Comment by wublack** [comment]
@horou-dsk 有解决这个问题吗？

**Comment by wublack** [comment]
@horou-dsk 你检查一下你的签名和key还有包名是不是正确？我把那些配置好，就不会报了

**Comment by caohuicong** [comment]
@horou-dsk 我一开始也是报了你的那个错误，我检查了一下，我是使用了百度地图控制台里面，ios的key值，我再创建一个android的 使用他的key值，就没这问题了

**Comment by GreatAuk** [comment]
一样的问题，我是因为更换了keystore文件，忘了重新生成百度地图的开发密钥了，还是用的之前的，也就是说开发密钥是错的。最骚的是百度地图还能显示 ，还能定位，只是不能使用Geocode了，整了很久才想到可能是这个问题
