### ISSUE TITLE
页面切换地图黑线，加上TextureMapView后闪退问题

### ISSUE THREAD

**Issue by chenqianlei** [qiuxiang/react-native-baidumap-sdk#170]
作者你好，如你说的那样加上TextureMapView后，地图黑线能解决了，但是第一次进地图页面会出现闪退问题，一般是在第一次登陆的时候，第二次token登陆闪退几率就较小，报错如下
![image](https://user-images.githubusercontent.com/35800740/53313146-f975d180-38f2-11e9-88e6-2d4c33b95832.png)
还望能给一些提示，谢谢

**Comment by qiuxiang** [comment]
这个错误看不出什么

**Comment by chenqianlei** [comment]
> 这个错误看不出什么

闪退给出的报错就只有这个。。。  黑线问题除了换TextureMapView，还有什么办法了吗

**Comment by qiuxiang** [comment]
安装测试版看看 react-native-baidumap-sdk@next

**Comment by chenqianlei** [comment]
> 安装测试版看看 react-native-baidumap-sdk@next

谢谢回复，测试版安装上有报错。问题我通过添加监听，然后页面切换时调用onPause()和onResume()方法刷新地图，黑线问题就没有了

**Comment by Aaron181** [comment]
> > 安装测试版看看 react-native-baidumap-sdk@next
> 
> 谢谢回复，测试版安装上有报错。问题我通过添加监听，然后页面切换时调用onPause()和onResume()方法刷新地图，黑线问题就没有了

你好，能说下具体解决步骤吗，谢谢

**Comment by chenqianlei** [comment]
> > > 安装测试版看看 react-native-baidumap-sdk@next
> > 
> > 
> > 谢谢回复，测试版安装上有报错。问题我通过添加监听，然后页面切换时调用onPause()和onResume()方法刷新地图，黑线问题就没有了
> 
> 你好，能说下具体解决步骤吗，谢谢

我是用的react-navigation的createBottomTabNavigator切换底部标签出现的黑线问题，https://blog.csdn.net/j550341130/article/details/81220317用这个方法跳转标签，并添加监听，添加MapView的paused属性就可以了

**Comment by 2ming** [comment]
@chenqianlei 是MapView.setStatus({paused: true}) 这样更新地图吗？

**Comment by 2ming** [comment]
@chenqianlei 没看到 map的 onPause()和onResume()
