### ISSUE TITLE
ios端单击地图的时候会调用onStatusChange事件，

### ISSUE THREAD

**Issue by les10281502** [qiuxiang/react-native-baidumap-sdk#173]
import React, { Component } from "react";
import { MapView,Initializer,Location,Geocode } from 'react-native-baidumap-sdk'
import { Image, StyleSheet, TouchableOpacity, View,TextInput,PermissionsAndroid,Dimensions  } from 'react-native'
import {Button} from "native-base";
import icon from '../../images/ic_my_location.png'
//地图的初始化很重要
Initializer.init('RsQHZLc0xCNCFLzgH3wfxya4PCEzPUzY').catch(e => alert.error(e));

import {
    Container,
    Header,
    Title,
    Icon,
    Text,
    Right,
    Body,
    Input,
    InputGroup,
    Content
} from "native-base";

import Iconfont from '../../components/utils/Iconfont'
import config from "../../components/utils/config";
import icon_center from '../../images/location.png'
import MyHeader from "../../components/header/header";

import MarkPannel from  '../../components/baidumap/markerPannel'
import CommonUtil from "../../components/utils/commons"

const sankhadeep = require("../../images/drawer-cover.png");
const positionIcon = require("../../images/position-icon.png");
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
const markerPicList= [
    [require('../../images/g0.png'), require('../../images/g1.png'), require('../../images/g2.png'), require

('../../images/g3.png'), require('../../images/g4.png'), require('../../images/g5.png'), require('../../images/g5+.png'), 

require('../../images/g10+.png'), require('../../images/g30+.png'), require('../../images/g50+.png'), require

('../../images/g99+.png')],
    [require('../../images/r0.png'), require('../../images/r1.png'), require('../../images/r2.png'), require

('../../images/r3.png'), require('../../images/r4.png'), require('../../images/r5.png'), require('../../images/r5+.png'), 

require('../../images/r10+.png'), require('../../images/r30+.png'), require('../../images/r50+.png'), require

('../../images/r99+.png')],
    [require('../../images/y0.png'), require('../../images/y1.png'), require('../../images/y2.png'), require

('../../images/y3.png'), require('../../images/y4.png'), require('../../images/y5.png'), require('../../images/y5+.png'), 

require('../../images/y10+.png'), require('../../images/y30+.png'), require('../../images/y50+.png'), require

('../../images/y99+.png')]
]

export default class myNavigation extends Component {

    constructor(props) {
        super(props);

        this.state = {
            markClickStatus : false,
            parking : [],
            parkingDetail : null,
            latitude: 32.45, longitude: 119.92,
            location:{latitude: 32.45, longitude: 119.92,},
            center:{latitude: 32.45, longitude: 119.92,},
        };
        this.longitude="119.92";
        this.latitude="32.45";

        // this.address = ''
        this.city = ''

    };
    //搜索功能
    search = () => {
        console.log("this.address==="+this.address)
        if(this.address){
            Geocode.search(this.address, this.city)
                .then(result => {
                    this.mapView.setStatus({ center: result }, 1000)
                    this.latitude=result.latitude;
                    this.longitude=result.longitude;
                    this.setState(result)
                    this.marker.select()
                    this.showNearbyParking();
                })
        }

    }

//查询周围的停车场
    showNearbyParking = (longitude,latitude)=> {
        let url = "app/tcdh/queryTCC";
        let searchObj = {};
        searchObj.tccb_wd = latitude;
        searchObj.tccb_jd = longitude;
        searchObj.dis = 5;//范围5km
        let that = this;
        CommonUtil.postDataPer(url,searchObj,function (data) {
            let dataObj = data.data;
            dataObj.map(function(temp){
                temp.longitude = temp.tccb_jd;
                temp.latitude = temp.tccb_wd;
            });
            if(data.resultCode == '0'){
                that.setState({
                    parking : dataObj
                });
            }
        })

    };

    async componentWillMount() {
        await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION);
        await Location.init();
        Location.setOptions({ gps: true });
        let those=this;
        //获取用户的经纬度
        Location.addLocationListener(location => {
            this.setState({location});
            let that=this;
            that.setState({
                center:{longitude:location.longitude,latitude:location.latitude}
            })
            that.mapViewReverse(location.latitude,location.longitude)
            those.showNearbyParking(location.longitude,location.latitude);
        });
        Location.start();

    }
    async componentDidMount(){
        this.listener.remove()
    }
    componentWillUnmount() {
        Location.stop();
    }
//定位
    location = () => {
        return (this.mapView.setStatus({ center: this.state.location }, 1000))
    };
    /**
     * 拖动地图
     * @param e
     */
    getCenterPosition = (e) =>{
        console.log("e"+JSON.stringify(e))
        let that = this;
        let lng = e.region.longitude;
        let lag = e.region.latitude;
        //this.mapView.setStatus({ center: {latitude: lag, longitude: lng} }, 1000);
        that.setState({
            center:{longitude:lng,latitude:lag}
        })
        that.showNearbyParking(lng,lag);
        //经纬度解析成地址
        that.mapViewReverse(lag,lng)
    };
//通过具体经纬度确定汉字地址
    mapViewReverse = (latitude,longitude) =>{
        Geocode.reverse({ latitude: latitude, longitude: longitude })
            .then(result => {
                try{
                    if(result.address){
                        console.log("result.address11=="+result.address)
                        this.setState({
                            address:result.address
                        })
                    }
                }catch (e) {
                }
            })
    };

    //点击事件
    onPress = Marker => {
        this.mapView.setStatus({
            center: Marker.coordinate,
            zoomLevel: this.status.zoomLevel + 1,
        }, 500)
    };

    mapViewClick = () =>{
        // alert("点击地图");
        this.setState({
            markClickStatus:false
        })
    };
//标记地图上的点
    markerClick = (temp) =>{
        console.log("temp="+JSON.stringify(temp))
        this.setState({
            markClickStatus:true,
            parkingDetail : temp
        })
    };
    picPosition(kcw, zcw) {
        let emptyCar = kcw || 0;
        let totalCar = zcw || (kcw || 0);
        let distance = totalCar - emptyCar > 0 ? totalCar - emptyCar : 0;
        let proportion = 0;
        let position = [0, 0];
        if (totalCar > 0) {
            proportion = Math.round(emptyCar / totalCar * 100);
        }
        if (proportion >= 0 && proportion < 10) {
            position = this.horizontalAndVerticalPosition(1, emptyCar);
        } else if (proportion >= 10 && proportion < 30) {
            position = this.horizontalAndVerticalPosition(2, emptyCar);
        } else {
            position = this.horizontalAndVerticalPosition(0, emptyCar);
        }
        return position;
    };

    horizontalAndVerticalPosition(horizontal, emptyCar) {
        let position = [0, 0];
        if (emptyCar >= 0 && emptyCar <= 5) {
            position = [horizontal, emptyCar];
        } else if (emptyCar > 5 && emptyCar <= 10) {
            position = [horizontal, 6];
        } else if (emptyCar > 10 && emptyCar <= 30) {
            position = [horizontal, 7];
        } else if (emptyCar > 30 && emptyCar <= 50) {
            position = [horizontal, 8];
        } else if (emptyCar > 50 && emptyCar <= 99) {
            position = [horizontal, 9];
        } else if (emptyCar > 99) {
            position = [horizontal, 10];
        }
        return position;
    };
    renderMarker = (temp) => {
        let position = this.picPosition(temp.tccb_kcws, temp.tccb_zcws)
        let x = parseInt(position[0])
        let y = parseInt(position[1])
        let markPoint=markerPicList[x][y]
        return (
            <View>
                <Image style={style.image} source={markPoint} />
            </View>
        )
    };
    render() {
        let that = this;
        const props = {
            onLoad:this.location,
            center:this.state.location,
            ref: ref => this.mapView = ref,
            style: StyleSheet.absoluteFill,
            zoomLevel:18,
            location:this.state.location,
            locationEnabled:true,
            onClick:this.mapViewClick,
            onStatusChange:this.getCenterPosition
        };
        const {navigate} = this.props.navigation;
        return(
            <Container>
                    <MyHeader text='停车导航'  navigate={navigate} isBack={true} backBtn={()=>this.props.navigation.goBack

()}/>
                    <View style={style.body}>
                        <View style={style.mapView}>
                            <MapView {...props}  >
                                {this.address &&
                                <MapView.Marker
                                    ref={ref => this.marker = ref}
                                    title={this.state.address}
                                    onPress={this.onPress}
                                    coordinate={this.state}
                                />
                                }
                                {
                                    this.state.parking.map(function(temp){
                                        return(
                                            <MapView.Marker
                                                key={temp.tccb_id}
                                                onPress={that.markerClick.bind(this,temp)}
                                                coordinate={{latitude:parseFloat(temp.latitude),longitude:parseFloat

(temp.longitude)}}
                                                view={that.renderMarker.bind(this,temp)}
                                            />
                                        )
                                    })
                                }
                            </MapView>
                            <View style={style.button}>
                                <TouchableOpacity onPress={this.location}>
                                    <Image style={style.icon} source={icon} />
                                </TouchableOpacity>
                            </View>
                            <View style={style.center}>
                                <Image style={style.icon_center} source={icon_center} />
                            </View>

                            {
                                this.state.markClickStatus ?
                                    <View style={style.showDetail}>
                                        <MarkPannel parkingDetail={this.state.parkingDetail} navigation = 

{this.props.navigation}/>
                                    </View>
                                    : <View/>
                            }
                        </View>
                        <View style={style.form}>
                            <TextInput
                                underlineColorAndroid="transparent"
                                defaultValue={this.state.address}
                                style={style.input}
                                returnKeyType="search"
                                placeholder="请输入地址名称"
                                placeholderTextColor="#9e9e9e"
                                onChangeText={text => (this.address = text)}
                                onSubmitEditing={this.search}
                            />
                            <Button style={{backgroundColor:"#e75d6d",borderRadius:8,height:30}} onPress={this.search}>
                                <Text style={{flex:1, fontSize:14,textAlign:'center',marginBottom:3}}>搜索</Text>
                            </Button>
                        </View>
                    </View>
            </Container>
        )
    }
}
const style = StyleSheet.create({
    button: {
        position: 'absolute',
        left: 16,
        bottom: 16,
        backgroundColor: '#fff',
        borderRadius: 40,
        elevation: 2,
    },
    icon: {
        width: 24,
        height: 24,
        margin: 12,
        tintColor: '#616161',
    },
    center:{
        position: 'absolute',
        left: (width - 46)/2,
        top: (height - 252)/2,
        elevation: 2,
    },
    icon_center: {
        width: 22,
        height: 33,
        margin: 12,
    },
    showDetail:{
        position: 'absolute',
        left: 10,
        bottom: 10,
        right:10,
        backgroundColor: '#fff',
        borderRadius: 5,
        elevation: 3,
        padding:0
    },
    image: {
        width: 22.5,
        height: 30,
    },
    input: {
        color: '#492f2f',
        fontSize: 16,
        height:40
    },
    body: {
        flex: 1,
        backgroundColor: '#fff',
    },
    form: {
        padding: 15,
        paddingTop:0
    },
    mapView: {
        flex: 1,
    },
});

**Comment by invokeCallback** [comment]
兄弟，你ios端难道没有进入地图就会一只调用onStatusChange方法么？？？

**Comment by invokeCallback** [comment]
兄弟，你这个是咋个解决的啊？？？求告知，感谢了！！！
