### ISSUE TITLE
可以兼容ios本地地图开发吗？

### ISSUE THREAD

**Issue by zheangrybear** [qiuxiang/react-native-baidumap-sdk#183]
依赖react-native-baidumap-sdk后，需要删除之前本地导入的百度开发包，在打开之前开发的本地页面后，直接卡死，没有报错，不能兼容本地地图开发吗？？

**Comment by qiuxiang** [comment]
你说的情况比较复杂，需要对 ios 开发比较熟悉，定位到出现问题的原因才好解决

**Comment by qiuxiang** [comment]
并不会不兼容，但工程的配置可能是个问题

**Comment by zheangrybear** [comment]
重新pod install 可以了，确实是配置哪里出了问题，但是没有确定哪里出了问题...

**Comment by zheangrybear** [comment]
找到原因了，本地使用地图，js 中也要初始化......尴尬.....
