### ISSUE TITLE
把MapView放在ScrollView里，滑动地图时，需要暂时屏蔽父级ScrollView的触发事件

### ISSUE THREAD

**Issue by linwenchao** [qiuxiang/react-native-baidumap-sdk#20]
如题

**Comment by qiuxiang** [comment]
详细说明下你的预期，还有实际存在的问题

**Comment by linwenchao** [comment]
把MapView内嵌在ScrollView或FlatList之类的本身有滑动事件响应的控件里时，
上下滑动时MapView本身的拖拽事件就被拦截了，
具体更多描述可参考 https://stackoverflow.com/questions/6546108/mapview-inside-a-scrollview

另，这个baidumap sdk做得实在好用，且更新频繁响应及时，非常感谢！
目前看，是否优先级比amap sdk要高？
想确认一下，如果baidumap sdk比amap sdk权重更高的话，我就用这个了，就是坐标要双向做多一重转换。

**Comment by collagy** [comment]
我也觉得baidu的地图要好一些  期待后续更多的功能

**Comment by linwenchao** [comment]
看到更新了，不过这问题在iOS上也存在啊 @qiuxiang

**Comment by qiuxiang** [comment]
之后再看
