### ISSUE TITLE
关于定位返回信息

### ISSUE THREAD

**Issue by Leijiawei** [qiuxiang/react-native-baidumap-sdk#21]
您好，我有个问题：
1.定位是返回的信息能否含有地址等详细信息，不只是经纬度

2.获取定位信息的详细地址是否只能通过Geocode.reverse获取

谢谢！！！
文字有点多不会英文了，sorry

**Comment by qiuxiang** [comment]
1. 不能在定位的时候就返回详细信息
2. 是的

主要是 ios 地图 SDK 的定位模块太简单了，只能返回基本定位数据，另一方面是希望保持模块功能单一独立。

**Comment by Leijiawei** [comment]
![image](https://user-images.githubusercontent.com/11434308/36891713-754998f4-1e3d-11e8-9ad9-d8a39bb88554.png)

![image](https://user-images.githubusercontent.com/11434308/36891754-9932164c-1e3d-11e8-84e3-ab27e04fc375.png)

我定位后返回的数据是第二张图的，能给看看是什么原因吗？

**Comment by collagy** [comment]
Geocode.reverse 返回的数据中没有县是为什么

**Comment by collagy** [comment]
在县的行政范围 district参数 为空

**Comment by Leijiawei** [comment]
Geocode.reverse返回的数据完全都是定位里的数据，怎样才只能有_55里的数据呢

**Comment by Leijiawei** [comment]
好的，谢谢。我再看看 example

**Comment by cnpmge** [comment]
> 在县的行政范围 district参数 为空

我也是这个问题，请问你解决了吗
