### ISSUE TITLE
请问想要实现战争迷雾的那种效果，要用什么来实现呢？

### ISSUE THREAD

**Issue by guihouchang** [qiuxiang/react-native-baidumap-sdk#249]
最近新增一个地图需求，需要制作一个探索功能，大致的功能是在全球覆盖一层灰色遮罩，然后人去过的地方要移除对应位置的这遮罩，请问要用什么组件来实现这样子的功能呢？

**Comment by qiuxiang** [comment]
SDK 没有提供这个功能
