### ISSUE TITLE
cocopod导入后yoga.cpp文件报错

### ISSUE THREAD

**Issue by WoAiLiMoChou** [qiuxiang/react-native-baidumap-sdk#25]
![image](https://user-images.githubusercontent.com/13573280/37077254-1e9256be-2215-11e8-9fdf-499d67860981.png)
运行报错

**Comment by collagy** [comment]
我出现这个问题的时候是因为 编译的目标ios版本设置错了  编译10.3报错 编译11.2不报错

**Comment by qiuxiang** [comment]
我自己也遇到过，但已经不记得具体是怎么回事，也没有再重现

**Comment by yezidd** [comment]
有什么解决方法吗我也遇到相同的问题

**Comment by WoAiLiMoChou** [comment]
我解决不了

**Comment by yezidd** [comment]
我跑起来了。我的rn版本0.52.0不行，然后看了作者的版本0.52.2完美运行。

**Comment by yezidd** [comment]
其他版本没试过，也懒得试了。

**Comment by qiuxiang** [comment]
可以确定是环境问题，在没有找到可重现的方法之前，该问题关闭
