### ISSUE TITLE
project ':react-native-baidumap-sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41

### ISSUE THREAD

**Issue by xfeng-github** [qiuxiang/react-native-baidumap-sdk#253]
添加依赖 yarn add react-native-baidumap-sdk 后无法编译通过了
![image](https://user-images.githubusercontent.com/57913284/96864884-b5f2b280-149b-11eb-9e6e-ce1e22f791a9.png)
该如何解决呢

**Comment by xfeng-github** [comment]
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] The following dependencies do not satisfy the required version:
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] project ':react-native-baidumap-sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
19:12:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org

**Comment by NapChen** [comment]
改下gradle的版本就行了，报错提示了要1.3.0或以上

**Comment by xfeng-github** [comment]
> 改下gradle的版本就行了，报错提示了要1.3.0或以上

好的， 多谢提醒

**Comment by junguoguo2017** [comment]
0.61.5需要改到什么版本 不会报错

**Comment by NapChen** [comment]
> 0.61.5需要改到什么版本 不会报错

`react-native-baidumap-sdk` 要改这个的gradle版本为1.3.0或者以上

**Comment by junguoguo2017** [comment]
> > 0.61.5需要改到什么版本 不会报错
> 
> `react-native-baidumap-sdk` 要改这个的gradle版本为1.3.0或者以上

依旧有其他问题
