### ISSUE TITLE
react native 0.54也无法运行

### ISSUE THREAD

**Issue by VictorYuan666** [qiuxiang/react-native-baidumap-sdk#27]
报错Print: Entry, ":CFBundleIdentifier", Does Not Exist
0.52没有问题

**Comment by qiuxiang** [comment]
我在运行 release 测试的时候就发现了，只是还没时间细看

**Comment by dioxide** [comment]
刚测试在RN 0.55.1  下, 只要使用<MapView.Marker /> 组件, 就会直接闪退, xcode上定位到了其他第三方组件的代码上.   而<MapView.Polyline />则正常. @qiuxiang
