### ISSUE TITLE
text.ios.js Unable to resolve module `UnimplementedView`

### ISSUE THREAD

**Issue by colagy** [qiuxiang/react-native-baidumap-sdk#29]
![e430394ee19c87c0b1368b2068cf638d](https://user-images.githubusercontent.com/37213080/37207245-150d4d60-23d7-11e8-8250-213e8f080bef.jpg)
node-modules/react-native-baidumap-sdk/lib/js/map-view/text.ios.js 报错
module.exports = require('UnimplementedView')
Unable to resolve module `UnimplementedView`

**Comment by qiuxiang** [comment]
你的版本不是最新的吧

**Comment by colagy** [comment]
最新版本也不行

**Comment by colagy** [comment]
你说的是什么最新版本  react native?  react-native-baidumap-sdk?  ios?

**Comment by qiuxiang** [comment]
自己对比 https://github.com/qiuxiang/react-native-baidumap-sdk/tree/master/lib/js/map-view

**Comment by colagy** [comment]
我怎么更新不到这个版本

**Comment by qiuxiang** [comment]
https://www.npmjs.com/package/react-native-baidumap-sdk

**Comment by colagy** [comment]
ok了  yarn锁了版本
