### ISSUE TITLE
打包报错  

### ISSUE THREAD

**Issue by colagy** [qiuxiang/react-native-baidumap-sdk#30]
![qq20180311-160124](https://user-images.githubusercontent.com/37213080/37251169-835c489c-2545-11e8-8046-2f2f95278489.png)
node_modules/react-native-baidumap-sdk/lib/js/map-view/text.js

**Comment by linwenchao** [comment]
把 map-view/index.js 中 9和18行注释掉后可解决上述报错
也就是说，把 MapView.Text 屏蔽掉 @colagy
