### ISSUE TITLE
我加入了SDK为什么还是会秒退

### ISSUE THREAD

**Issue by chenxiong666** [qiuxiang/react-native-baidumap-sdk#32]
![image](https://user-images.githubusercontent.com/31265809/37385720-3bb9db06-2790-11e8-90db-0d27aae11747.png)

**Comment by qiuxiang** [comment]
你进行初始化了？https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/docs/installation.md#%E5%88%9D%E5%A7%8B%E5%8C%96%E9%87%8D%E8%A6%81

**Comment by chenxiong666** [comment]
import { Initializer } from 'react-native-baidumap-sdk'

Initializer.init().catch(e => console.error(e))
安卓是这样初始化的吗

**Comment by chenxiong666** [comment]
我是这样写的

**Comment by chenxiong666** [comment]
好了 ，不好意思 我是纯前端的 对native不了解，谢谢解答

**Comment by qiuxiang** [comment]
那你需要看 logcat，看看是什么导致崩溃的
