### ISSUE TITLE
安卓返回闪退是为什么呢

### ISSUE THREAD

**Issue by Hermaner** [qiuxiang/react-native-baidumap-sdk#33]
安卓返回闪退是为什么呢  只要引入使用mapview了

**Comment by qiuxiang** [comment]
请提供出错的 logcat

**Comment by Hermaner** [comment]
@qiuxiang 
直接react-native run-android  没有任何报错，我用android studio运行查看报错日志
03-25 17:49:12.692 6867-6867/com.afanti.monkeydoor A/libc: Fatal signal 11 (SIGSEGV) at 0x00000020 (code=1), thread 6867 (anti.monkeydoor)

**Comment by Hermaner** [comment]
@qiuxiang 我用你自己的demo示例也是如此

**Comment by qiuxiang** [comment]
logcat 要尽可能详细，最好是截图

**Comment by Hermaner** [comment]
![1521972782742](https://user-images.githubusercontent.com/12965639/37873930-432429c0-3058-11e8-88b1-579002e592ce.jpg)
只有这个，闪退调就没信息了

**Comment by qiuxiang** [comment]
这就没办法了，没有什么有用的信息

**Comment by Hermaner** [comment]
@qiuxiang  没有接单类似的反馈碰到这样的问题吗？我这边是百分百闪退，用你自己的demo都是如此，
使用adb logcat *:S ReactNative:V ReactNativeJS:命令没有任何错误信息返回，只有android studio返回了上面的那一行错误。搜了下是不是要返回的时候将mapview给Destroy掉？我不懂原生开发

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-baidumap-sdk/releases/download/v0.5.0/example.apk 就是项目 example 编译出来的。

**Comment by Hermaner** [comment]
安卓模拟器的问题
