### ISSUE TITLE
安卓模拟器引入后闪退

### ISSUE THREAD

**Issue by sanriqing** [qiuxiang/react-native-baidumap-sdk#39]
给了2核4g，据你另一个项目说是没有硬件加速所以闪退，但是有其他法子解决吗？

**Comment by lourain** [comment]
@sanriqing 我的也是请问 你怎么解决的？

**Comment by lourain** [comment]
我昨天在真机上试了下，也是闪退。

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/docs/installation.md#初始化重要
