### ISSUE TITLE
MapView 点击添加marker的问题

### ISSUE THREAD

**Issue by pingxiaodou** [qiuxiang/react-native-baidumap-sdk#42]
问题描述：在MapView中点击一点然后将Marker定在该点（只有一个Marker）
预期效果：点击后Marker出现在点击的点
实际效果：点击后Marker位置并没有变动，拖拽地图移动后Marker才能显示在指定的位置
代码如下：`import React, {Component} from 'react'
import {Alert, StyleSheet} from 'react-native'
import {MapView} from 'react-native-baidumap-sdk'

export default class Dynamic extends Component {
    static navigationOptions = {title: 'Dynamically add and remove'}

    constructor(props){
        super(props)
        this.state = {
            coordinate : {}
        }
    }

    addMarker = (coordinate) => {
        this.setState({
            coordinate
        })
    }

    render() {
        return (
            <MapView style={StyleSheet.absoluteFill} onClick={this.addMarker} >
                {
                    this.state.coordinate.latitude ? (
                        <MapView.Marker coordinate={this.state.coordinate}/>
                    ) : null
                }
            </MapView>
        )
    }
}`

![200e109f-3b82-4b0c-8d76-1b543933b1d2](https://user-images.githubusercontent.com/23648004/38763801-f6559d76-3fd5-11e8-9bfa-7f7d17c90d84.gif)

**Comment by qiuxiang** [comment]
SDK 默认就是这样的，之前也有意识到这个问题，只是当时没有马上想到解决办法，现在想来只能 Hack，在 `setCoordinate` 之后触发一次地图状态更新。https://github.com/qiuxiang/react-native-baidumap-sdk/commit/38b3fcb424cb26ef8e5b2ac912df8adc659810c3#diff-d95e05742d5031009291f2f4de4c8bfdR45

**Comment by pingxiaodou** [comment]
多谢帮助
