### ISSUE TITLE
为什么我的安装完了，运行就出现错误

### ISSUE THREAD

**Issue by yunakeji** [qiuxiang/react-native-baidumap-sdk#44]
我的RN版本 0.46.4  运行出现下面错误

src\main\java\cn\qiuxiang\react\baidumap\BaiduMapPackage.kt: (12, 1): Class 'B
aiduMapPackage' is not abstract and does not implement abstract member public ab
stract fun createJSModules(): (Mutable)List<Class<out JavaScriptModule!>!>! defi
ned in com.facebook.react.ReactPackage
:react-native-baidumap-sdk:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-baidumap-sdk/blob/54065a87bc075129c1cb93886c6419201a9db655/package.json#L39
