### ISSUE TITLE
安卓端在初始化时报错 permission check error

### ISSUE THREAD

**Issue by ho1messi** [qiuxiang/react-native-baidumap-sdk#46]
在执行 Initializer.init('XXX').catch(e => console.error(e)) 这句时报错 permission check error

04-19 21:35:21.735  7795  7826 E ReactNativeJS: { [Error: permission check error] framesToPop: 1, code: '101' }

**Comment by qiuxiang** [comment]
这就是 key 和 权限的问题，请自行检查

**Comment by ho1messi** [comment]
![screenshot_2018-04-19-22-03-19](https://user-images.githubusercontent.com/11469361/38996612-29d26656-441e-11e8-9d06-82666e5837c6.png)


问题详情如上，请问能判断出是key有问题还是权限有问题么

目前已经配置的权限如下：

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.GET_TASKS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />

**Comment by qiuxiang** [comment]
应该是可以区分的，有时间再看下

**Comment by qiuxiang** [comment]
我都忘了。。返回的 Error 对象已经带了 code 的，然后看官方的错误码定义：http://lbsyun.baidu.com/index.php?title=androidsdk/guide/addition-func/errorcode 。
<img width="747" alt="image" src="https://user-images.githubusercontent.com/1709072/39314183-42799d04-49a6-11e8-951b-2ccb399e49de.png">

比如你这里 `code: '101'`，就是根本没有配置 key 的意思。

**Comment by GreatAuk** [comment]
@qiuxiang 我项目上，android在执行执行 Initializer.init('XXX').catch(e => console.error(e)) 这句时报错 permission check error，只有把catch去掉，好像能正常使用。发现example上也没有捕获错误，https://github.com/qiuxiang/react-native-baidumap-sdk/blob/2045182c2f4a87a9cbfd70d0726e4540b7c1a33d/example/index.js#L7
