### ISSUE TITLE
ios 运行报错：ld: framework not found BaiduMapAPI_Base

### ISSUE THREAD

**Issue by auven** [qiuxiang/react-native-baidumap-sdk#48]
请问大神这是什么原因，我按照你的配置文档配置了，pod install 安装成功了，但是 build 不成功
![291524887120_ pic_hd](https://user-images.githubusercontent.com/23731087/39391648-a35ddd0e-4ad9-11e8-8b70-32a9da5b8ff5.jpg)

**Comment by qiuxiang** [comment]
截图你 xocde 的 sidebar

**Comment by auven** [comment]
我从官方下载了 sdk，拖进工程里，可以 **build 成功** 了。
<img src="https://user-images.githubusercontent.com/23731087/39391823-8840e86a-4adc-11e8-9d8b-ad83de3fb3fa.jpg" />

但是为啥显示的 **都是网格线，没有地图出来** 。
<img width="300" src="https://user-images.githubusercontent.com/23731087/39391832-aa4ac41c-4adc-11e8-8b68-70aad2e7b56a.jpg" />

**Comment by qiuxiang** [comment]
初始化？

**Comment by auven** [comment]
有初始化啊，用的是你 example 的代码

**Comment by auven** [comment]
可以了，example 的 key 估计是安卓的吧，我换成了自己的 key

**Comment by qiuxiang** [comment]
这哪是 android key 的问题呀，我写在 example 的 key 就是 ios 的，但你的包名不可能和我的一样，肯定要用自己的 key 啊。
