### ISSUE TITLE
附近的圆圈问题

### ISSUE THREAD

**Issue by gaowei887** [qiuxiang/react-native-baidumap-sdk#49]
这个圆圈设置颜色后会一直往上铺，颜色会越来越深
 <MapView.Circle
                        center={this.state.circleCenter}
                        radius={500}
                        strokeWidth={1}
                        strokeColor="rgba(162, 165, 167, 1.0)"
                        fillColor="rgba(0, 0, 0, 0)"
                    />
就是这个

**Comment by qiuxiang** [comment]
截图？

**Comment by gaowei887** [comment]
就是这个问题，这个圈的边框会随着时间越来越深

**Comment by qiuxiang** [comment]
基本可以肯定是你代码的问题，除非你能提供可重现的代码

**Comment by gaowei887** [comment]
这就是重新啊，我就是用你这个插件调用画了一个 circle 而已啊，然后这个 map 就好把这个 circle 越绘越深

**Comment by qiuxiang** [comment]
你有看过 example？那么为什么 example 的没有问题？

**Comment by gaowei887** [comment]
你 demo 设置的颜色是全透明的，所以不会铺上很多层

**Comment by qiuxiang** [comment]
你能确定，在 example 用同样的颜色能重现你所说的问题？

**Comment by qiuxiang** [comment]
另外，你说的不对，example 里用的颜色明明是半透明

**Comment by gaowei887** [comment]
iOS 上有这个问题，Android 上还没看，应该也会有的

**Comment by qiuxiang** [comment]
然而并没有出现你说的问题

<img src="https://user-images.githubusercontent.com/1709072/39828131-925d7354-53ec-11e8-8269-e1c270d104e3.png" width=300>

所以你能提供图片说明？我不想浪费时间在一个不明确的问题上，而你从始至终都没有提供足够的信息。

**Comment by qiuxiang** [comment]
而你的理解显然很有问题，如果真的存在你说的这个问题，那么基本会是原生的问题，你又如何有把握认为 android 也会出现？（况且这个问题并不能重现）

**Comment by lyy1125** [comment]
这个问题解决了吗？iOS我也遇到这个问题

**Comment by mengzhe1973** [comment]
ios上我也遇见这个问题了，怎么解决这个问题啊

**Comment by AtoyGG** [comment]
同问啊！不停的放大缩小就会加深圈的颜色

**Comment by qiuxiang** [comment]
所以有谁能提供一个视频说明下吗，我自己并没有发现这个问题，光说我并不能认识这个问题的存在
