### ISSUE TITLE
Attempt to invoke virtual method

### ISSUE THREAD

**Issue by iizhangchao** [qiuxiang/react-native-baidumap-sdk#51]
![qq 20180507100548](https://user-images.githubusercontent.com/19889539/39681664-3bb2ee0e-51de-11e8-92f9-a255ae5fba91.jpg)

rn 0.55.3
react-native-baidumap-sdk: 0.5.4

在不使用 Initializer.init这个方法时，能获取到定位的经纬度，去换取具体城市时取不到。就加了这个init方法就报错了

**Comment by qiuxiang** [comment]
你没有设置 key 吧

**Comment by iizhangchao** [comment]
设置来的，Initializer.init('T5G8a7uPAq4Hz5lbNYdSXlI9G0s8fIzY')

**Comment by iizhangchao** [comment]
不调用 Initializer.init 时能取到 经纬度 
![qq 20180507101535](https://user-images.githubusercontent.com/19889539/39681964-c00765e4-51df-11e8-9693-281bddf14407.png)

去换取具体位置的时候就会报这个错 
![qq 20180507101557](https://user-images.githubusercontent.com/19889539/39681980-d32e5088-51df-11e8-8733-c5890e4c36f2.jpg)

**Comment by qiuxiang** [comment]
我是说在 AndroidManifest 里的 key，还有，我在安装说明里也说了，android 是不需要提供参数的

**Comment by iizhangchao** [comment]
我去检查了下，确实是这key，我没放进 application里，放在外面，重新编译一道就OK，感谢作者

**Comment by iizhangchao** [comment]
init传key，我是看了你在init这个方法里面做了判断的，所以我就没去做区分
