### ISSUE TITLE
定位开启后，什么情况下，逆地理编码result的结果为空

### ISSUE THREAD

**Issue by AtoyGG** [qiuxiang/react-native-baidumap-sdk#52]

**Comment by AtoyGG** [comment]
@qiuxiang

**Comment by qiuxiang** [comment]
定位与逆地理编码没有任何关系

**Comment by AtoyGG** [comment]
这就好奇怪了，走定位了，但是逆地理编译出来的城市为空。

**Comment by qiuxiang** [comment]
我怎么觉得你的理解有问题，哪里有逆地理编码？

**Comment by AtoyGG** [comment]
就是定位之后，走监听方法，项目需要当前位置信息，然后用了reverse方法

**Comment by qiuxiang** [comment]
有看过 example？

https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/example/examples/search/geocode-reverse.js

**Comment by AtoyGG** [comment]
看过啦，就是部分机型，定位后逆地理编码有问题。

**Comment by qiuxiang** [comment]
逆地理编码和定位有什么关系？两者是独立的模块呀

**Comment by AtoyGG** [comment]
这个我知道，逆地理编码不得依赖于定位监听
this.listener = Location.addLocationListener((location)这个方法嘛
  我给reverse嵌套到这个方法里面了
有的机型就会出现城市为空的情况

**Comment by qiuxiang** [comment]
如果真的存在问题，那么大概是逆地理编码的问题，而失败其实是有信息的，只是我暂时忽略掉了

https://github.com/qiuxiang/react-native-baidumap-sdk/blob/d75e0eb301b980c16178cd1c3ea8cf3849976327/lib/android/src/main/java/cn/qiuxiang/react/baidumap/modules/BaiduMapGeocodeModule.kt#L17

https://github.com/qiuxiang/react-native-baidumap-sdk/blob/d75e0eb301b980c16178cd1c3ea8cf3849976327/lib/ios/Modules/RCTGeocodeModule.m#L53

有能力的话可以自己调试下原生的代码
