### ISSUE TITLE
MapView.marker  android报错：width and height must be > 0

### ISSUE THREAD

**Issue by yangbo5207** [qiuxiang/react-native-baidumap-sdk#53]
```js
<MapView.Marker
      key={index}
      view={() => <Icon name="start" />}
      coordinate={{ latitude: item.latitude, longitude: item.longitude }}
    />
```
我创建了一个页面组件MapDetail包含如上代码。
+ 当我给MapView.Marker添加view属性时
+ 导航使用react navigation
+ 当直接从Home页面导航进入MapDetail页面一切正常
+ 当通过某一个列表页的某一项点击导航进入MapDetail则报错

```
width and height must be > 0

createBitmap
Bitmap.java:841
createBitmap
Bitmap.java:820
...
```

**Comment by qiuxiang** [comment]
这个问题在另一个地图项目也出现过，大概是因为渲染自定义 View 的时候，对应的原生 View 还没准备好，但是我自己并没有找到重现的方法。这个错误要忽略掉是很容易的，但结果肯定是自定义 View 无法显示。

另外还是要建议，尽可能用原生图片 `image` 而不是 `view`，前者的性能比后者好太多。

**Comment by yangbo5207** [comment]
@qiuxiang 对，如果组件被渲染的次数稍微多一点，就很容易出现这个问题，我想知道在使用的时候应该如何避免这种情况呢，如果组件的渲染次数已经控制到最少了

**Comment by qiuxiang** [comment]
我是想知道什么情况下才会出现出现这个问题，你有能重现的代码吗

**Comment by yangbo5207** [comment]
@qiuxiang 我使用view时，当render次数多一点，比如接口数据过来了render一次，或者改了某个状态多render了一次就会很容易出现这个问题(android)。目前已经使用原生图片的方式避免了这个问题

**Comment by kekegdsz** [comment]
同上。。。也经常出现这个问题，原生图片不会

**Comment by kekegdsz** [comment]
![image](https://user-images.githubusercontent.com/17893790/40818754-4864760c-658b-11e8-8df5-89f18ae4f2a8.png)目前处理方法，当为0时默认给个值，至少不会爆红

**Comment by kekegdsz** [comment]
是的，再没有好办法之前，只能这样处理了，爆红天尴尬了，图片显示不出来，我还可以解释解释
