### ISSUE TITLE
遇到的几个问题

### ISSUE THREAD

**Issue by xiehui999** [qiuxiang/react-native-baidumap-sdk#54]
1，自定义View图片加载问题，使用resizeMode时图片无法加载
2，页面1，页面2都有地图时，如果我第一个页面的地图设置了固定高度（在某个view中），非全屏，跳转到页面2（全屏或者半屏），页面1的地图会覆盖在页面2上。
3，当地图以固定高度，如高度100，放到ScrollView中时，滑动卡顿严重。
希望看到给个解决思路，特别是第二种和第三种情况。谢谢

**Comment by qiuxiang** [comment]
你这是 android 吧？

第一点需要测试，可能不能解决。

第二点是 MapView 的问题，把 MapView 改为 TextureView 可以解决

https://github.com/qiuxiang/react-native-baidumap-sdk/blob/d75e0eb301b980c16178cd1c3ea8cf3849976327/lib/android/src/main/java/cn/qiuxiang/react/baidumap/mapview/BaiduMapView.kt#L24

我还在评估到底应该是默认使用 TextureView 还是提供两种组件。

第三点需要测试过才知道什么情况。

**Comment by xiehui999** [comment]
是android,图片那个问题是如果加载的是url，则需要再次刷新下才能显示（如你demo中那个自定义，如果那个不刷新时间，那个图片就显示不出来。），本地图片加载正常，但是resizeMode之后就不显示了，

**Comment by qiuxiang** [comment]
远程图片的问题我在文档里有说明：https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/docs/marker.md#update-android-only
