### ISSUE TITLE
如何跳转到百度地图导航的api不知道有没有

### ISSUE THREAD

**Issue by kekegdsz** [qiuxiang/react-native-baidumap-sdk#55]
如何跳转到百度地图导航的api不知道有没有

**Comment by qiuxiang** [comment]
暂时没用

**Comment by kekegdsz** [comment]
不知道你发现没有，前一个界面有地图时，跳转第二个界面，第二界面也有地图，两个地图会重叠

**Comment by qiuxiang** [comment]
两个 MapView 的问题我是知道的，是 MapView 渲染机制的问题，这里 https://github.com/qiuxiang/react-native-baidumap-sdk/issues/54#issuecomment-388522945 有提到怎么解决，但这个问题在我开发的 app 并没有出现，需要重新测试。
