### ISSUE TITLE
Cricle 圆形覆盖物通过state设置半径不重新渲染，半径不起作用。

### ISSUE THREAD

**Issue by wangwenrong** [qiuxiang/react-native-baidumap-sdk#57]
问题：通过react的state设置MapView.Circle的radius半径属性就第一次起作用，setState后不重新渲染，还是第一次的值。
暂时解决方法：设置MapView.Circle的key属性等于radius通过react的机制重新渲染。

**Comment by qiuxiang** [comment]
ios 还是 android？

**Comment by wangwenrong** [comment]
@qiuxiang ios
