### ISSUE TITLE
MapView.Marker自定义callout，没有关闭的api

### ISSUE THREAD

**Issue by wangwenrong** [qiuxiang/react-native-baidumap-sdk#59]
MapView.Marker自定义callout，没有关闭的api，只有点击任意处关闭，并没有单独处理的点击关闭api

**Comment by qiuxiang** [comment]
这个接口的应用场景？

**Comment by wangwenrong** [comment]
@qiuxiang 点击这个标记展开一个详细信息的框，框上边有个x是关闭，没法设置关闭

**Comment by qiuxiang** [comment]
但是要知道 CustomCallout 里都没法做交互

**Comment by beikeku** [comment]
请问找到解决方法了吗 我们设计也需要有个关闭按钮
