### ISSUE TITLE
Andorid 4.4.4 从地图页面返回黑屏闪退

### ISSUE THREAD

**Issue by lifbliu** [qiuxiang/react-native-baidumap-sdk#60]
真机的版本为4.4.4，从地图页面返回上一页时黑屏闪退。没有看到任何报错，请问这个什么原因导致的，有没有什么办法可以解决。

**Comment by qiuxiang** [comment]
要用 android studio 看 logcat

**Comment by lifbliu** [comment]
@qiuxiang 
你好，log里面报的这个错。
  a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x0
05-24 03:09:36.961 4986-4986/com.cmos.netapp A/libc: Fatal signal 11 (SIGSEGV) at 0x00000018 (code=1), thread 4986 (com.cmos.netapp)

**Comment by qiuxiang** [comment]
最好截图

**Comment by lifbliu** [comment]
@qiuxiang 这是崩溃时的截图
![_20180525150358](https://user-images.githubusercontent.com/20511379/40530879-00280f38-602d-11e8-9ceb-fdf6311dc300.png)

**Comment by lifbliu** [comment]
作者你好，我觉得这可能是地图组件没有销毁的问题。我从一个地图页面，直接跳转至另一个带有地图的页面时，上一个页面的地图组件还在。而且也没有办法清除。请问有什么方法可以在componentWillUnmount里面把地图组件手动清除了？
![image](https://user-images.githubusercontent.com/20511379/40535402-9a06bbb4-603b-11e8-9076-d6e6f26ccb46.png)

**Comment by lifbliu** [comment]
@qiuxiang 希望可以添加一个onDestory方法

**Comment by qiuxiang** [comment]
地图重叠的问题不是简单的 destory 可以解决的，一旦 destory 了上一层的地图，返回的时候就用不了了。这是 MapView 和 RN 的问题，目前的解决方法只能自己把 MapView 改为 TextureMapView。

你上面的截图也没有截到终点，你表出来的那里并没有说明什么，而下面看起来才是重点。

**Comment by lifbliu** [comment]
感谢回复，这是app闪退时抓到的日志。buz不知能否在这里面看出来问题的所在。至于你说的MapView改为TextureMapView的意思是改动源码吗？ 
![1527488279](https://user-images.githubusercontent.com/20511379/40600735-1ed07e3e-6285-11e8-9c29-8772b8f22f7e.png)

**Comment by qiuxiang** [comment]
改这里 https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/lib/android/src/main/java/cn/qiuxiang/react/baidumap/mapview/BaiduMapView.kt#L24

从 logcat 看，这个问题很可能是 SDK 的 bug，或不兼容问题

**Comment by qiuxiang** [comment]
你得换一个设备看看

**Comment by lifbliu** [comment]
谢谢作者，地图重叠的问题已经解决了。我换了一个模拟器，和真机（小米3移动版，安卓版本为4.4.4），还是有从地图页面返回时闪退的问题。我用的模拟器都是安卓4.4.4的版本，所以我想是不是因为安卓版本过低的问题。在安卓5，6,7等虚拟机上就没有闪退的问题。

**Comment by qiuxiang** [comment]
那应该就是 SDK 的兼容性问题

**Comment by lifbliu** [comment]
谢谢，已经跟产品商量不兼容低版本安卓了。

**Comment by cnpmge** [comment]
请问地图重叠问题是怎么解决的呢？麻烦您说一下，我也遇到了这个问题

**Comment by cnpmge** [comment]
你好，我会持续关注您的，请您帮忙解决，谢谢
