### ISSUE TITLE
不显示地图是怎么回事，也没走初始化失败的回掉，也无报错

### ISSUE THREAD

**Issue by qq895627041** [qiuxiang/react-native-baidumap-sdk#62]

**Comment by hswoaini555** [comment]
key值不对,我前两天也遇到了这个问题,弄了很久,最后更改了,sha1后重新生成的key就可以正常使用了.

**Comment by qq895627041** [comment]
我的是容器高度不够没显示，尴尬 ，现在有一个新问题，我 在一个栈里面 ，两次使用定位，第一次的可以，第二次定位失效，而且返回会导致app奔溃

**Comment by qiuxiang** [comment]
@qq895627041 其他问题请另开 issue，并且提供可重现的方法。
