### ISSUE TITLE
onDragEnd 拖拽标记结束后,不返回经纬度

### ISSUE THREAD

**Issue by hswoaini555** [qiuxiang/react-native-baidumap-sdk#68]
这是我返回的内容
Proxy {dispatchConfig: {…}, _targetInst: FiberNode, isDefaultPrevented: ƒ, isPropagationStopped: ƒ, _dispatchListeners: ƒ, …}
[[Handler]]
:
Object
[[Target]]
:
SyntheticEvent
[[IsRevoked]]
:
false

案例返回的是{longitude: 116.397972,latitude: 39.806901} 

代码是我从案例直接复制的,两边完全一样,但返回的结果却不一样.

key是正确的,地图可以正确显示,其他地图组件都正常使用.

查了很多资料也没找到原因,我想问一下出现这样结果的原因以及解决的办法

**Comment by qiuxiang** [comment]
有试过 example？

**Comment by hswoaini555** [comment]
插件里面的其他组件都是可以正常使用的,就是为独这个draggable  onDragEnd拖拽结束后返回的结果,和你的example返回的结果是不一样的.

**Comment by qiuxiang** [comment]
![](https://i.imgur.com/hHRJoWD.png)

我用一个新项目测试，并没有问题呀

**Comment by hswoaini555** [comment]
Duplicate of #
![qq 20180605095158](https://user-images.githubusercontent.com/34708579/40950693-61092c20-68a6-11e8-9fe5-f1228013a684.png)

![qq 20180605095137](https://user-images.githubusercontent.com/34708579/40950702-6879a25a-68a6-11e8-8144-32f500266c3f.png)
![screenshot_20180605_095026](https://user-images.githubusercontent.com/34708579/40950707-6e50e792-68a6-11e8-980e-657a505a0a48.jpg)
![qq 20180605095238](https://user-images.githubusercontent.com/34708579/40950732-7b3e3446-68a6-11e8-93ea-4b9037b42fc3.png)

上面是你的example代码,和我的页面代码.下面是我分别alert和console出来的结果,就返回的不是经纬度

**Comment by qiuxiang** [comment]
你的版本是什么？

**Comment by hswoaini555** [comment]
![1](https://user-images.githubusercontent.com/34708579/40950920-5c623b66-68a7-11e8-889d-332e79dfeec3.png)

**Comment by qiuxiang** [comment]
不是很确定，感觉好像和 react-native-amap3d 的同名事件冲突了，你试着移除 react-native-amap3d 试试

**Comment by hswoaini555** [comment]
嗯,好,我先把react-native-amap3d移除了看看,谢谢了
