### ISSUE TITLE
使用范地理编码时报错

### ISSUE THREAD

**Issue by kekegdsz** [qiuxiang/react-native-baidumap-sdk#72]
使用范地理编码时报错

**Comment by kekegdsz** [comment]
![image](https://user-images.githubusercontent.com/17893790/41137851-0a49b17c-6b10-11e8-9b43-556d8b89d606.png)

**Comment by qiuxiang** [comment]
Duplicate of #70

**Comment by kekegdsz** [comment]
thank you
