### ISSUE TITLE
地图初始化定位问题

### ISSUE THREAD

**Issue by EverGitHub** [qiuxiang/react-native-baidumap-sdk#73]
每次都是北京天安门那个定位，怎么初始化地图定位为当前位置呢？

export default class BaiduMap extends Component {
    state = {}

    async componentDidMount() {
        await Location.init()
        Location.setOptions({ gps: true })
        this.listener = Location.addLocationListener(location => {
            this.setState({ location })
            this.mapView.setStatus({ center: this.state.location }, 1000)
        })
        Location.start()
    }

    componentWillUnmount() {
        Location.stop();
        this.listener.remove()
    }

    location = () => {
        return (this.mapView.setStatus({ center: this.state.location }, 1000))
    };

    render() {
        return(
        <View style={StyleSheet.absoluteFill}>
            <MapView
                onLoad={this.location}
                ref={ref => this.mapView = ref}
                style={StyleSheet.absoluteFill}
                zoomLevel={20}
                location={this.state.location}
                locationEnabled
            />
            <View style={style.button}>
                <TouchableOpacity onPress={this.location}>
                    <Image style={style.icon} source={icon} />
                </TouchableOpacity>
            </View>

        </View>
    )
    }
}

如果这样实现的话，在定位迅速的情况下，this.state.location为undefined，说明还没有把位置信息传递给state.location，如果加一个settimeout，延迟1秒执行的话，就会有一个明显的位置移动现象，就是先显示北京天安门，然后移动定位到当前位置。
怎么解决初始化地图定位为当前位置呢？谢谢。

**Comment by qiuxiang** [comment]
不明白你在困惑什么，在已知坐标的情况下用 center 属性或 setStatus 方法不就行了？

**Comment by qiuxiang** [comment]
> 在定位迅速的情况下，this.state.location为undefined
具体什么时候，哪里的 this.state.location为undefined？

> 如果加一个settimeout，延迟1秒执行的话
为什么要加 setTimeout？解决了什么？在哪加？

**Comment by qiuxiang** [comment]
所以这是你自己要解决的问题，在实际的情况中，就是没办法做到定位马上能得到数据，但你可以缓存最后一次定位的数据，在地图加载的时候默认用最后一次定位的坐标作为中心。

**Comment by EverGitHub** [comment]
好吧，thanks
