### ISSUE TITLE
问题：1. marker自定义图片有问题  看下面问题描述 2. marker 的view自定义图标，但会导致onPress失效

### ISSUE THREAD

**Issue by KloveML** [qiuxiang/react-native-baidumap-sdk#75]
### 1. marker自定义图片有问题图标不显示
```js
<Marker
       coordinate={{longitude:116.387112,latitude:39.920977}}
       image="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1529946881082&di=1b2a0d1e6d2161b3616e8e0815522ec2&imgtype=0&src=http%3A%2F%2Fimg.zcool.cn%2Fcommunity%2F01bc205939f932a8012193a3e33430.jpg"
       title="This is a image marker" 
/>
```
### 2. 利用marker的view属性，自定义图标，自定义内容onPress失效
```js
_renderView = () => (
    <Button
      title="button"
      onPress={() => {
        console.log('click');
      }}
    />
  );

 <Marker
      key={item.key}
      coordinate={item.coordinate}
      view={this._renderView}
/>
```
---

**Comment by KloveML** [comment]
@qiuxiang

**Comment by qiuxiang** [comment]
请仔细阅读文档 https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/docs/marker.md

**Comment by KloveML** [comment]
@qiuxiang 你的文档 我都看几十遍了  iOS源码也看了  你这样配置根本不行  不知道你有没有调试过

**Comment by KloveML** [comment]
@qiuxiang https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/example/examples/marker/image.js

**Comment by KloveML** [comment]
@qiuxiang 你可以看下你的例子  https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/example/examples/marker/image.js  按照你的例子 即使设置成image="flag" 也没用   你的文档 本身就有很多不完整的地方 我大多参照你例子看的  你例子如果能确定不问题的话  那我这样配置的问题在哪呢  而且image的参数说明是什么  存放uri  还是其他字符串  你的lib/js里面的源码 只是用标记是string类型  其他没有标注

**Comment by KloveML** [comment]
@qiuxiang 还有你这个文档能解释   view属性自定义图标onPress失效的问题？如果不使用view

**Comment by invokeCallback** [comment]
@qiuxiang 大神，我也是这个问题，ios真机。问题1、marker自定义图片能显示，然后当我点击marker或地图任意地点的时候，都会执行onStatusChange函数，因为我是前端，着实没看你文档里面的东西<ios 对应：[UIImage imageNamed:image]>。问题2、拖动地图，通过onStatusChange函数获取到新的中心点，然后赋值给center的时候，就会一直重复调用onStatusChange这个函数，导致死循环。问题3、初始进入地图都会调用onStatusChange函数，这个也是没懂为什么！！！麻烦求告知一下，谢谢了！谢谢了！谢谢了！辛苦了！辛苦了！辛苦了！

**Comment by qiuxiang** [comment]
onStatusChange 的时候不要设置 center，这样做没有任何意义，设置 center 必触发 onStatusChange

**Comment by invokeCallback** [comment]
@qiuxiang 大神，Android上是可以设置的，但是ios却不能设置。能不能告知一下问题1和问题3的解决方法啊。辛苦了。

**Comment by qiuxiang** [comment]
onStatusChange 被调用有什么问题？

**Comment by invokeCallback** [comment]
@qiuxiang 大神，我刚刚试了Android的，我初始化进入的时候并不会执行onStatusChange，然后iOS真机却会执行；Android的只有拖动地图的时候才会执行onStatusChange，点任意地方都不会执行这个函数，但是iOS的却是点任意都会执行onStatusChange函数，导致marker上面的onPress函数失效，跟这楼的问题是一样的。我加你的q，怕你的隐私泄露，那麻烦你加我一下q 316056563。感谢了，大神！！！

**Comment by qiuxiang** [comment]
抱歉。我暂时没有打算在这个项目多花精力
