### ISSUE TITLE
地图初始化报错：undefined is not an object (evaluating 'BaiduMapInitializer.init')

### ISSUE THREAD

**Issue by h406621397** [qiuxiang/react-native-baidumap-sdk#76]
undefined is not an object (evaluating 'BaiduMapInitializer.init')
init
    E:\RN\BaiduMapSDK_APP\node_modules\react-native-baidumap-sdk\lib\js\modules\initializer.js:9:33
<unknown>
    E:\RN\BaiduMapSDK_APP\App.js:18:17
loadModuleImplementation
    E:\RN\BaiduMapSDK_APP\node_modules\metro\src\lib\polyfills\require.js:214:12
guardedLoadModule
    E:\RN\BaiduMapSDK_APP\node_modules\metro\src\lib\polyfills\require.js:148:36
_require
    E:\RN\BaiduMapSDK_APP\node_modules\metro\src\lib\polyfills\require.js:132:20
<unknown>
    E:\RN\BaiduMapSDK_APP\index.js:2
loadModuleImplementation
    E:\RN\BaiduMapSDK_APP\node_modules\metro\src\lib\polyfills\require.js:214:12
guardedLoadModule
    E:\RN\BaiduMapSDK_APP\node_modules\metro\src\lib\polyfills\require.js:141:45
_require
    E:\RN\BaiduMapSDK_APP\node_modules\metro\src\lib\polyfills\require.js:132:20
global code
    
你好，我的RN版本是 0.55.4，初始化调用 Initializer.init() 这个方法的时候报错，是我RN版本太高了的原因吗？

**Comment by h406621397** [comment]
`import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View
} from 'react-native';

import { Initializer } from 'react-native-baidumap-sdk'
Initializer.init('6s1BDd7jUHhzUV8S8E3kMEyAKfqkKPrw');

type Props = {};
export default class App extends Component<Props> {

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
      </View>
    );
  }
}`

我写在APP.js里面的，index.js引入了这个文件。 不知道这样写对不对

**Comment by qiuxiang** [comment]
现在不是 js 写法的问题，而是你根本就没编译

**Comment by h406621397** [comment]
嗯，昨天是因为我没有执行 react-native link 。 今天用自己的key在新项目试的，本来debug和release都只显示网格不显示地图的，现在我啥都没改，debug又好了，可以显示地图，但是打成release包后还是不行，只显示网格。

**Comment by qiuxiang** [comment]
你需要确保 init 是成功的

**Comment by h406621397** [comment]
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.baidu.android.bbalbs.common.util.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.baidu.lbsapi.auth.d) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.baidu.lbsapi.auth.f) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
.........

打release包的时候出现了很长很长一段warning，好像很多类不能被编译？

**Comment by qiuxiang** [comment]
wanning 那也是 sdk 的

**Comment by lhy58** [comment]
我也遇到过同样的问题

**Comment by lhy58** [comment]
请问怎么解决?
