### ISSUE TITLE
Marker 定义view属性后，onPress属性失效

### ISSUE THREAD

**Issue by xuanheScript** [qiuxiang/react-native-baidumap-sdk#77]
Marker 定位view属性后，onPress属性失效（不是在view中定义的onPress）
注：在ios下，android正常
```
render(){
   return (
      <MapView {...props}>
           <MapView.Cluster
               onPress={this.onPress}
               ref={ref => this.cluster = ref}
               markers={this.markers}
               renderMarker={this.renderMarker}
               renderCluster={this.renderCluster}
           />
      </MapView>
   )
}
renderMarker = item => (
  <MapView.Marker
       view={() => (
         <View>
            <Text>This is a custom view marker</Text>
         </View>
       )}
       key={item.extra.key}
       title={item.extra.key}
       coordinate={item.coordinate}
       onPress={() => {
           alert(1)
       }}
  />
)
```
点击marker后，没有执行onPress

**Comment by xuanheScript** [comment]
![image](https://user-images.githubusercontent.com/19216775/42078484-454c84d4-7baf-11e8-9ec7-6ff131ae6194.png)
定义view属性后，onPress确实没有执行

**Comment by xuanheScript** [comment]
@qiuxiang 不知道你是否有时间，这看起来像一个遗留的问题

**Comment by qiuxiang** [comment]
没有问题呀

```javascript
  renderMarker = item => (
    <MapView.Marker
      key={item.extra.key}
      title={item.extra.key}
      view={() => <Text>D</Text>}
      onPress={() => Alert.alert('d')}
      coordinate={item.coordinate}
    />
  )
```

<img width="460" alt="image" src="https://user-images.githubusercontent.com/1709072/42082485-ae4ab31a-7bba-11e8-9c29-9c57e399f4f5.png">

**Comment by xuanheScript** [comment]
经测试，>=0.53版本 自定义view属性,onPress会失效。
回滚到0.52版本了，难受····

**Comment by qiuxiang** [comment]
你应该一开始就说明 RN 版本，iOS 自定义 View 的问题，在 README 就已经重点声明了，这个 bug 暂时没有时间去研究。

另外，我会建议能用自定义图片就不要用自定义 View。

**Comment by JacquesYW** [comment]
@qiuxiang   上层加个透明图片覆盖view全部，是否可以实现点击事件，我web是这么弄的

**Comment by AcYangle** [comment]
![image](https://github.com/qiuxiang/react-native-baidumap-sdk/assets/15205440/689097fe-3659-45d5-9012-24d2aab6ed48)
添加这段代码可解决
