### ISSUE TITLE
初始化后，地图就是白屏的了

### ISSUE THREAD

**Issue by friendlove** [qiuxiang/react-native-baidumap-sdk#78]
初始化后，地图就是白屏的了

**Comment by qiuxiang** [comment]
确定 init 成功了？

**Comment by qiuxiang** [comment]
版本信息？设备信息？截图？

**Comment by friendlove** [comment]
@qiuxiang  小米mix2s  ，红米2，     "react-native": "0.55.4",

**Comment by friendlove** [comment]
@qiuxiang
`import React from 'react';
import {View, Text} from 'react-native'
import Header from '../common/components/BackHeader'
import {Location, MapView} from 'react-native-baidumap-sdk'

class App extends React.Component {

    state = {location: null};

    constructor(props) {
        super(props);
        // this.init().then();
    }

    async init() {
        await Location.init();
        Location.addLocationListener(location => alert(JSON.stringify(location)));
        Location.start()
    }

    render() {
        return (
            <View style={{flex: 1}}>
                <Header/>
                <MapView
                    center={{latitude: 39.2, longitude: 112.4}}
                    onLoad={() => console.warn('onLoad')}
                    onClick={point => console.warn(point)}
                    onStatusChange={status => console.warn(status)}/>
            </View>
        );
    }
}

export default App;
`

**Comment by qiuxiang** [comment]
你有设置 width、height？

**Comment by friendlove** [comment]
@qiuxiang 谢谢，这样可以了。`<View style={{flex: 1}}>
                <Header/>
                <MapView
                    style={{flex: 1,width:'100%',height:'100%'}}
                    center={{latitude: 39.2, longitude: 112.4}}
                    onLoad={() => console.warn('onLoad')}
                    onClick={point => console.warn(point)}
                    onStatusChange={status => console.warn(status)}/>
            </View>`
