### ISSUE TITLE
地图空白只显示网格（真机和Genymotion模拟器下都是这种情况）

### ISSUE THREAD

**Issue by kevinchensd** [qiuxiang/react-native-baidumap-sdk#8]
地图空白只显示网格（真机和Genymotion模拟器下都是这种情况）
{
  "name": "qiuxiangbdmapexample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-baidumap-sdk": "^0.3.2",
    "react-navigation": "^1.1.2"
  },
  "devDependencies": {
    "babel-jest": "22.4.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.0",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

![_20180222172344](https://user-images.githubusercontent.com/26289472/36530110-2f107e82-17f5-11e8-8352-57c7f54f2550.jpg)

**Comment by qiuxiang** [comment]
基本可以确定是 key 的问题

**Comment by kevinchensd** [comment]
应该是权限问题，稍等我试一下

**Comment by qiuxiang** [comment]
哦。。你这是运行了 example，确实是 key 的问题，因为我用的 keystore 是个人的，你需要自己去申请一个

**Comment by qiuxiang** [comment]
不是权限问题

**Comment by qiuxiang** [comment]
我干脆重新生成一个 keystore 放到项目里来吧

**Comment by kevinchensd** [comment]
我这边不是keystore文件的问题，而是Key的配置问题，默认项目配置的debug keystore是没法使用百度地图的，可以让release和debug使用同一个keystore文件，如可以在build.gradle里面这样配置，加上debug部分：

` buildTypes {
release {
minifyEnabled enableProguardInReleaseBuilds
proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
signingConfig signingConfigs.release
}

    debug {
        signingConfig signingConfigs.release
    }

}`

**Comment by kevinchensd** [comment]
@qiuxiang 主要还是例子更重要，很多插件功能开发的不少，但是大家都不会用，也不可能提供详细的文档说明，所以不断完善的example才是插件的第一生产力；
