### ISSUE TITLE
定位方法概率性不回调

### ISSUE THREAD

**Issue by xtcan** [qiuxiang/react-native-baidumap-sdk#80]
async componentDidMount() {
    // 定位当前位置
    await Location.init()
    Location.setOptions({ gps: true })
    this.listener = Location.addLocationListener(location => {
      console.log('获取位置成功')
      console.log(location)

      this.setState({
        center: { longitude: location.longitude, latitude: location.latitude },
      })
    })
    Location.start()
  }

  componentWillUnmount() {
    Location.stop()
    this.listener.remove()
  }

进入页面，例如demo中Location in MapView，获取位置成功方法概率性不回调，有时候会回调，有时候不会回调

**Comment by qiuxiang** [comment]
试过 example？

**Comment by xtcan** [comment]
就是example，安卓

**Comment by qiuxiang** [comment]
如果是 example 的话，完全没有问题呀

**Comment by qiuxiang** [comment]
有重现的方法？我在 example 都没有遇到过

**Comment by moma555** [comment]
定位方法只在首次进入页面有回调 to 定位方法概率性不回调
