### ISSUE TITLE
IOS NativeModules出错

### ISSUE THREAD

**Issue by friendlove** [qiuxiang/react-native-baidumap-sdk#81]
pod install后
运行起来ios ，在初始化的时候（Initializer.init）出错
![image](https://user-images.githubusercontent.com/21053212/42407360-29b20b56-81ed-11e8-98fc-459e1b69c83b.png)

**Comment by qiuxiang** [comment]
看不出来是什么错误

**Comment by friendlove** [comment]
`
/**
 * Created by chenai on 2017/10/1.
 */
/**
 * Created by friendlove-pc on 2017/6/16.
 */
// @flow
import React from 'react';
import {View, Text} from 'react-native'
import Header from '../common/components/BackHeader'
import {Location, MapView, Geocode} from 'react-native-baidumap-sdk'
import {Initializer} from 'react-native-baidumap-sdk'
Initializer.init('com.chenai.logistics').catch(e => console.error(e));

class App extends React.Component {

    state = {location: global.location, searchResult: undefined};

    constructor(props) {
        super(props);
        this.init().then();

    }

    async init() {
        await Location.init();
        Location.addLocationListener(location => {
            this.setState({location});
            global.location = location;
        });
        Location.start();
        const searchResult = await Geocode.search('充电桩');
        console.warn(searchResult);
    }

    render() {
        console.warn('location', this.state.location);
        return (
            <View style={{flex: 1}}>
                <Header/>
                <MapView
                    locationEnabled
                    location={this.state.location}
                    style={{flex: 1, width: '100%', height: '100%'}}
                    center={this.state.location ? this.state.location : {latitude: 26.08, longitude: 119.3}}
                    // onLoad={() => console.warn('onLoad')}
                    // onClick={point => console.warn(point)}
                    // onStatusChange={status => console.warn(status)}
                >
                    {
                        this.state.searchResult &&
                        <MapView.Marker
                            view={() => (
                                <View>
                                    <Text>充电桩</Text>
                                </View>
                            )}
                            coordinate={this.state.searchResult}
                        />
                    }


                </MapView>
            </View>
        );
    }
}

export default App;

`

**Comment by friendlove** [comment]
![image](https://user-images.githubusercontent.com/21053212/42431188-9ae2b8fe-8376-11e8-9a8f-a2af46a5469e.png)
@qiuxiang

**Comment by qiuxiang** [comment]
你上面说是 Initializer.init 导致的，但看你这些截图没有什么关系呀

**Comment by KingAmo** [comment]
我也遇到这个错误了

**Comment by cnpmge** [comment]
我这目前也遇到了这个错误，Geocode.search的时候ios直接报nativemodule这个错误

**Comment by cnpmge** [comment]
Error
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:397)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:72
