### ISSUE TITLE
0.52.3 Android版本无法运行

### ISSUE THREAD

**Issue by wk1017553772** [qiuxiang/react-native-baidumap-sdk#82]
看似是gradle 的问题
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.9.4
  Yarn: 0.27.5
  npm: 5.4.2
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.1 => 0.52.3

![image](https://user-images.githubusercontent.com/4082286/42512082-41db8086-8486-11e8-8a4c-18d1a70fe7c2.png)

**Comment by qiuxiang** [comment]
这需要你自己解决，类似的错误参考：https://github.com/qiuxiang/react-native-amap3d/issues/164 https://github.com/qiuxiang/react-native-amap3d/issues/136 或自己 google "transformClassesWithDexForDebug" 的解决方法

**Comment by wk1017553772** [comment]
我升级了gradle 版本就没问题了  应该是百度的包对gradle版本有要求吧
