### ISSUE TITLE
ios Marker报错,mapview正常，android正常

### ISSUE THREAD

**Issue by wenhuihuang** [qiuxiang/react-native-baidumap-sdk#85]
在ios下运行MapView.Marker报Thread 1: signal SIGABRT错，*bundleUrl为nil。报错位置为以下方法
+ (NSBundle *)bundle {
    static NSBundle *_bundle = nil;
    if (_bundle == nil) {
        NSURL *bundleUrl = [[NSBundle bundleForClass:[self class]] URLForResource:@"react-native-baidumap-sdk" withExtension:@"bundle"];
        _bundle = [NSBundle bundleWithURL:bundleUrl];
    }
    return _bundle;
}
，如果不用Marker就正常显示地图。安卓正常运行正常。请问是哪里出错了，是不是资源没有引进去导致的？

**Comment by qiuxiang** [comment]
资源肯定是会被 pods 引用，我测试也没有问题，问题在于你的配置

**Comment by 2248157705** [comment]
我是pods 引用，没有发现博主的资源文件
![2018-07-23 8 25 38](https://user-images.githubusercontent.com/4066040/43051864-12a3a6f6-8e52-11e8-87c3-bfefd9eaaab6.png)
![2018-07-23 8 25 52](https://user-images.githubusercontent.com/4066040/43051869-19455900-8e52-11e8-8903-edd810c86f9c.png)
![2018-07-23 8 28 12](https://user-images.githubusercontent.com/4066040/43051896-66a43c66-8e52-11e8-830e-38d14b8efe3e.png)
请问博主的资源文件在哪个位置，能否截个图👀

**Comment by qiuxiang** [comment]
react-native-baidumap-sdk.bundle 是 pods 配置的：

https://github.com/qiuxiang/react-native-baidumap-sdk/blob/903d22b7643a886ac587a3e6b7f4c52eb07eb5ea/lib/ios/react-native-baidumap-sdk.podspec#L17
