### ISSUE TITLE
 react-native-baidumap-sdk (from `../node_modules/react-native-baidumap-sdk/lib/ios`) was resolved to 0.5.4, which depends on       BaiduMapKit (~> 3.4.0)

### ISSUE THREAD

**Issue by cizhaoyang** [qiuxiang/react-native-baidumap-sdk#88]
[!] CocoaPods could not find compatible versions for pod "BaiduMapKit":
  In snapshot (Podfile.lock):
    BaiduMapKit (= 3.2.1)

  In Podfile:
    react-native-baidumap-sdk (from `../node_modules/react-native-baidumap-sdk/lib/ios`) was resolved to 0.5.4, which depends on
      BaiduMapKit (~> 3.4.0)

Specs satisfying the `BaiduMapKit (= 3.2.1), BaiduMapKit (~> 3.4.0)` dependency were found, but they required a higher minimum deployment target.
这个在ios上pod引入的时候报的

**Comment by qiuxiang** [comment]
删掉 Podfile.lock 重新 pod install 试试
