### ISSUE TITLE
pod install之后项目启动不起来

### ISSUE THREAD

**Issue by hoshealee** [qiuxiang/react-native-baidumap-sdk#91]
1. pod install 成功。
2. 配置完成后启动cocoapod对应项目文件，folly提示缺少boost头文件，
#include <boost/iterator/iterator_adaptor.hpp> 提示文件不存在，boost中确实没有该文件。

**Comment by qiuxiang** [comment]
RN 版本？

**Comment by hoshealee** [comment]
我使用了0.45和0.52两个版本尝试。都没有成功。

**Comment by hoshealee** [comment]
使用pod总是怪怪的，有种不安全感。
