### ISSUE TITLE
标记层级问题？

### ISSUE THREAD

**Issue by ImagineZzf** [qiuxiang/react-native-baidumap-sdk#92]
例如，两个标记距离比较近，其中一个选中时，怎么让它层级增加一级，不让另一个标记遮住？

**Comment by qiuxiang** [comment]
我记得被选中的 marker 就自动比其他 marker 高一个层级的

**Comment by ImagineZzf** [comment]
初始化渲染后marker的层级就固定了，选中的marker也还是原来的层级，略显尴尬😅，不知道有没有解决的办法？ @qiuxiang

**Comment by qiuxiang** [comment]
android 还是 ios？

**Comment by ImagineZzf** [comment]
主要测试了ios @qiuxiang

**Comment by qiuxiang** [comment]
我看了下 ios sdk 文档，都没有 zIndex，这个问题是没法解决了
