### ISSUE TITLE
安卓出现崩溃的错误堆栈，麻烦看看

### ISSUE THREAD

**Issue by cbbccj** [qiuxiang/react-native-baidumap-sdk#93]
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
出错堆栈

1	com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
2	com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:30)
3	cn.qiuxiang.react.baidumap.modules.BaiduMapGeocodeModule$geoCoder$2$1.onGetReverseGeoCodeResult(BaiduMapGeocodeModule.kt:46)
4	com.baidu.platform.core.b.e.a(Unknown Source:11)
5	com.baidu.platform.base.c.run(Unknown Source:17)
6	android.os.Handler.handleCallback(Handler.java:790)
7	android.os.Handler.dispatchMessage(Handler.java:99)
8	android.os.Looper.loop(Looper.java:164)
9	android.app.ActivityThread.main(ActivityThread.java:6600)
10	java.lang.reflect.Method.invoke(Native Method)
11	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
12	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-baidumap-sdk/issues/70#issuecomment-395002953
