### ISSUE TITLE
如何移除定位监听事件？

### ISSUE THREAD

**Issue by ImagineZzf** [qiuxiang/react-native-baidumap-sdk#98]
如题，有Location.addLocationListener定位监听事件，如何把这个监听事件移除？因为我这边首页需要获取定位，而城市选择列表页面也需要获取定位，添加两个定位监听事件，会造成定位概率性不获取的情况。

**Comment by badboyweb** [comment]
async componentDidMount() {
    await Location.init()
    Location.setOptions({ gps: true })
    this.listener = Location.addLocationListener(location => {
      this.setState({ location })
    })
    Location.start()
  }

  componentWillUnmount() {
    Location.stop()
    this.listener.remove()
  }
这段代码应该可以帮助你

**Comment by ImagineZzf** [comment]
@qiuxiang 移除监听事件方法没问题，应该是概率性获取不到定位的问题，我再想想办法，谢谢啦🙏
